const express = require('express');
const {signup, login, getMe, updateMe, changePassword, deleteMe,forgotPassword,resetPassword,logout} = require('../controllers/authController');
const {protect} = require('../middleware/auth');
const validate = require('../middleware/validate');
const authRateLimit = require('../middleware/authRateLimit');
const router = express.Router();
router.post('/signup', authRateLimit, validate(['fullName', 'email','password']), signup);
router.post('/login',authRateLimit, validate(['email', 'password']),login);
router.post('/logout', logout);
router.post('/forgot-password',authRateLimit, validate(['email']),forgotPassword);
router.post('/reset-password',authRateLimit, validate(['token', 'newPassword']), resetPassword);
router.get('/me',protect,getMe);
router.patch('/me', protect, updateMe);
router.patch('/change-password', protect, validate(['currentPassword', 'newPassword']), changePassword);
router.delete('/me', protect, deleteMe);
module.exports = router;